name: Automated Renpho Garmin Sync

on:
  schedule:
    - cron: '0 */6 * * *' # Wakes up automatically every 6 hours
  workflow_dispatch:     # Keeps your manual run button active

jobs:
  sync-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Sync Dependencies
        run: |
          pip install requests
          pip install garminconnect

      - name: Run Cloud Synchronization
        run: |
          python sync_script.py --renpho-email "ganesh.gsundaram@gmail.com" --renpho-password "B0urnessa1nt" --garmin-email "ganesh.sundaram@yahoo.com" --garmin-password "TamanSeras1"
